[package]
name = "readmerger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bio = "1.4.0"
clap = { version = "4.4.6", features = ["derive"] }
flate2 = "1.0.28"
glob = "0.3.1"
zstd = "0.13.0"
